version: '3'
services:

#####################
### WebApp Nodejs
#####################
  webapp:
    restart: on-failure
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - node_network

#####################
### Nginx Proxy
#####################
  proxy:
    restart: on-failure
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network

networks:
  node_network: